apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - aspnetapp.yaml
patches:
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: aspnetapp
        namespace: aspnetapp
      spec:
        type: LoadBalancer